services:
  web:
    image: ghcr.io/surreymagpie/nginx-php:latest
    container_name: $CONTAINER_NAME
    ports:
      - $WEBSERVER_PORT:80
    environment:
      - WEBROOT=$WEBROOT
      - DRUSH_OPTIONS_URI=$DRUSH_OPTIONS_URI
    volumes:
      - .:/var/www/html:Z,rw
      # Optionally can mount your SSH keys so
      # container can communicate with remote sites
      # - $HOME/.ssh:/root/.ssh:Z,rw

  db:
    image: docker.io/library/mariadb:10.6.16
    container_name: mariadb
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql

  # mailhog:
  #   image: docker.io/mailhog/mailhog:latest
  #   container_name: mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   # disable saving logs
  #   logging:
  #     driver: 'none'

volumes:
  db-data:
